from gpiozero import TonalBuzzer
from gpiozero.tones import Tone
from time import sleep

lst  = [261.32, 293.66, 329.62, 369.99, 391.99, 440.00, 493.88, 523.25, 587.32, 659.25, 739.98, 783.99 ]   # 도 레 미 파 솔 라 시 도 레

timeList = [0.5, 0.25, 1.0, 1.5]
# 4분음표,8분음표, 2분음표, 4분+ 반

b = TonalBuzzer(14)

############### 사랑을 했다
b.play(lst[6])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[6])
sleep(timeList[1])
b.stop()
b.play(lst[8])
sleep(timeList[3])
b.stop()

################## 우리가 만나
sleep(timeList[1])
b.play(lst[6])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[6])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[3])
b.stop()

##################### 지우지 못할
sleep(timeList[1])
b.play(lst[6])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[1])
b.stop()
sleep(0.1)
b.play(lst[5])
sleep(timeList[0])
b.stop()

################# 추억이 됐다
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
sleep(timeList[0])
b.stop()

################# 볼만한멜로드라마
sleep(timeList[1])
b.play(lst[6])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[6])
sleep(timeList[1])
b.stop()
b.play(lst[8])
sleep(timeList[3])
b.stop()

################# 괜찮은 결말
sleep(timeList[1])
b.play(lst[6])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[6])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[3])
b.stop()


################# 그거면 됐다
sleep(timeList[1])
b.play(lst[6])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[0])
b.stop()

################# 널사랑했다
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
sleep(timeList[0])
b.stop()

################# 우리가 만든 lo o ove 시나리오
sleep(timeList[1])
b.play(lst[6])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()

b.play(lst[9])
sleep(timeList[0])
b.stop()
b.play(lst[8])
sleep(timeList[1])
b.stop()
b.play(lst[6])
sleep(timeList[1])
sleep(timeList[1])
b.stop()

b.play(lst[5])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[6])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[3])
b.stop()

################# 이젠 조 며 어 엉 이 꺼지고
sleep(timeList[1])
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()


b.play(lst[9])
sleep(timeList[0])
b.stop()
b.play(lst[8])
sleep(timeList[1])
b.stop()
b.play(lst[6])
sleep(timeList[1])
sleep(timeList[1])
b.stop()

b.play(lst[5])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[3])
b.stop()


################# 마지막 페 이지 를 넘기면
sleep(timeList[1])
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[0])
b.stop()


b.play(lst[9])
sleep(timeList[1])
b.stop()
b.play(lst[11])
sleep(timeList[1])

b.stop()
b.play(lst[9])
sleep(timeList[1])
sleep(timeList[0])
b.stop()

b.play(lst[9])
sleep(timeList[1])
b.stop()
b.play(lst[11])
sleep(timeList[1])
b.stop()
b.play(lst[9])
sleep(timeList[1])
b.stop()
b.play(lst[8])
sleep(timeList[3])
b.stop()

################# 조용히 마 아 악 을 내리고
sleep(timeList[1])
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()


b.play(lst[9])
sleep(timeList[0])
b.stop()
b.play(lst[8])
sleep(timeList[1])
b.stop()
b.play(lst[6])
sleep(timeList[1])
sleep(timeList[0])
b.stop()

b.play(lst[5])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[1])
b.stop()
b.play(lst[5])
sleep(timeList[1])
b.stop()
b.play(lst[4])
sleep(timeList[3])
b.stop()

